### ISSUE TITLE
Cutwire schematic

### ISSUE THREAD

**Issue by XSsive** [AJMartel/FPS_Bomb_Simulator#1]
Hi, how are you wiring the cutwires? I've been working on something very similar to this and I'd just need to work on that

**Comment by AJMartel** [comment]
I use a PCF8574 (Remote8-Bit I/O Expander for I2C Bus), and connect to the first 4 wires.
The wires are connected like push buttons, using pull up resistors.
You can read the pins if a wire is cut it will read high, if not cut the circuit pulls the pin low.

**Comment by AJMartel** [comment]
Question answered
